CREATE EXTENSION PG_TRGM;
CREATE EXTENSION UNACCENT;

CREATE OR REPLACE FUNCTION arr_to_s(arr TEXT []) RETURNS TEXT IMMUTABLE LANGUAGE SQL AS $$
SELECT lower(unaccent(array_to_string(arr, ' '))) $$;

CREATE TABLE IF NOT EXISTS PESSOAS (
    ID UUID DEFAULT gen_random_uuid(),
    Apelido VARCHAR(32) CONSTRAINT ID_PK PRIMARY KEY,
    Nome VARCHAR(100),
    NASCIMENTO CHAR(10),
    STACK VARCHAR(32) [],
    BUSCA TEXT GENERATED ALWAYS AS (
        arr_to_s(STACK || ARRAY [APELIDO, NOME])
    ) STORED
);
CREATE INDEX CONCURRENTLY IF NOT EXISTS IDX_BUSCA_TGRM ON PESSOAS USING GIST (BUSCA GIST_TRGM_OPS(SIGLEN = 64));
